name: crush_app
description: A boilerplate for Flutter Projects using BLoC Architecture

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^9.2.2
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  dio: ^5.7.0
  equatable: ^2.0.5
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.14
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  iconsax_plus: ^1.0.0
  intl: ^0.19.0
  intl_utils: ^2.8.7
  json_annotation: ^4.9.0
  # agora_chat_sdk: ^1.2.0
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  zego_zimkit: ^1.18.13 #pour le chat
  zego_uikit_prebuilt_call: ^4.16.14 #ui pour le call
  zego_uikit_signaling_plugin: ^2.8.7
  zego_express_engine: ^3.18.0
  firebase_core: ^3.8.1
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/GeneralSans-Extralight.otf
          weight: 200
        - asset: assets/fonts/GeneralSans-ExtralightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/GeneralSans-Light.otf
          weight: 300
        - asset: assets/fonts/GeneralSans-LightItalic.otf
          weight: 300
        - asset: assets/fonts/GeneralSans-Regular.otf
          style: normal
        - asset: assets/fonts/GeneralSans-Italic.otf
          style: italic
        - asset: assets/fonts/GeneralSans-Medium.otf
          weight: 500
        - asset: assets/fonts/GeneralSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/GeneralSans-Semibold.otf
          weight: 600
        - asset: assets/fonts/GeneralSans-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/GeneralSans-Bold.otf
          weight: 700
        - asset: assets/fonts/GeneralSans-BoldItalic.otf
          weight: 700
          style: italic

fluttergen:
  output: lib/src/generated
  line_length: 120

  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
  class_name: I18n
  main_locale: en
  arb_dir: lib/src/core/i18n/l10n
  output_dir: lib/src/core/i18n
